# Generated by Django 4.0.2 on 2023-03-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_history_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='coordinates',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
